version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: newsdb
    restart: unless-stopped
    environment:
      POSTGRES_DB: newsdb
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    command: 
      - "postgres"
      - "-c"
      - "listen_addresses=*"
      - "-c"
      - "max_connections=100"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d newsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - appnet

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Подключение к БД
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      # Секреты
      JWT_SECRET: ${JWT_SECRET}
      AES_SECRET: ${AES_SECRET}

      # Директория для загрузок
      UPLOAD_DIR: "/app/uploads"
      
      # SSL настройки
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_CERTIFICATE: "/etc/ssl/certificate.crt"
      SERVER_SSL_CERTIFICATE_PRIVATE_KEY: "/etc/ssl/certificate.key"
      SERVER_SSL_TRUST_CERTIFICATE: "/etc/ssl/certificate_ca.crt"
    ports:
      - "8300:8300"
    volumes:
      # Монтируем директорию для загрузок и SSL сертификаты
      - uploads_volume:/app/uploads
      - ./ssl:/etc/ssl:ro
    networks:
      - appnet

  client:
    build: ./olymp_schools-client-main
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - appnet
    depends_on:
      - app

volumes:
  postgres_data:
  uploads_volume:

networks:
  appnet:
    driver: bridge