# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/newsdb
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret (64+ ???????? ??? HS512)
jwt.secret=ThisIsASecureSecretKeyForJWT1234567890123456789012345678901234567890

# AES Secret (????? 32 ??????? ??? AES-256)
aes.secret=ThisIsASecureAESKey12345678901234

# Server
server.port=8300

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true